const request=async<T>(url:string,options?:RequestInit):Promise<T>=>{const res=await fetch(url,options);if(!res.ok){let message=res.statusText;try{const body=await res.json();message=body.detail||message}catch{}throw new Error(message)}return res.json()}
export const api={
 dashboard:()=>request<any>('/api/dashboard'),videos:()=>request<any[]>('/api/videos'),runs:()=>request<any[]>('/api/runs'),
 settings:()=>request<any>('/api/settings'),saveSettings:(body:any)=>request<any>('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),
 upload:(file:File,onProgress:(n:number)=>void)=>new Promise<any>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/videos');xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-Filename',encodeURIComponent(file.name));xhr.upload.onprogress=e=>e.lengthComputable&&onProgress(Math.round(e.loaded/e.total*100));xhr.onload=()=>xhr.status<300?resolve(JSON.parse(xhr.responseText)):reject(new Error(JSON.parse(xhr.responseText).detail||'Upload thất bại'));xhr.onerror=()=>reject(new Error('Mất kết nối'));xhr.send(file)}),
 deleteVideo:(id:string)=>request(`/api/videos/${id}`,{method:'DELETE'}),validate:(body:any)=>request('/api/configs/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),
 createRun:(body:any)=>request<any>('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),run:(id:string)=>request<any>(`/api/runs/${id}`),cancelRun:(id:string)=>request(`/api/runs/${id}/cancel`,{method:'POST'}),deleteRun:(id:string)=>request(`/api/runs/${id}`,{method:'DELETE'}),result:(id:string)=>request<any>(`/api/runs/${id}/result`),
 detections:(id:string,start:number,end:number)=>request<any[]>(`/api/runs/${id}/detections?start_ms=${start}&end_ms=${end}`),
 bestFrame:(id:string,eventId:string,start:number,end:number)=>request<{timestamp_ms:number}>(`/api/runs/${id}/events/${encodeURIComponent(eventId)}/best-frame?start_ms=${start}&end_ms=${end}`),
 saveAnnotations:(id:string,rows:any[])=>request(`/api/runs/${id}/annotations`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows)}),review:(id:string)=>request(`/api/runs/${id}/review`,{method:'POST'}),reopen:(id:string)=>request(`/api/runs/${id}/reopen`,{method:'POST'}),evaluation:(id:string)=>request<any>(`/api/runs/${id}/evaluation`)
 ,exportReview:async(id:string,rows:any[]):Promise<Blob>=>{const response=await fetch(`/api/runs/${id}/export.xlsx`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows)});if(!response.ok){let message=response.statusText;try{message=(await response.json()).detail||message}catch{}throw new Error(message)}return response.blob()}
}
